from __future__ import annotations

import logging
import os
from typing import Any, Dict, Tuple

from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine
from sqlalchemy.engine.url import URL, make_url
from sqlalchemy.exc import OperationalError, SQLAlchemyError
from sqlalchemy.orm import declarative_base, sessionmaker

from app import config as APP_CONFIG

LOG = logging.getLogger(__name__)

PRIMARY_DB_URL = APP_CONFIG.PRIMARY_DB_URL
LOCAL_DB_URL = APP_CONFIG.LOCAL_DB_URL
ENV_DATABASE_URL = APP_CONFIG.DATABASE_URL


def _render_url(url: URL) -> str:
    return url.render_as_string(hide_password=True)


def _build_engine(url: URL) -> Engine:
    kwargs: Dict[str, Any] = {"future": True, "pool_pre_ping": True}
    backend = url.get_backend_name()
    if backend.startswith("mysql"):
        kwargs["pool_recycle"] = 1800
        kwargs["connect_args"] = {"connect_timeout": 3}
    elif backend == "sqlite":
        kwargs["connect_args"] = {"check_same_thread": False}
    return create_engine(url, **kwargs)


def _is_unknown_database(exc: OperationalError) -> bool:
    message = str(exc).lower()
    if "unknown database" in message:
        return True
    args = getattr(exc.orig, "args", ())
    if args:
        code = args[0]
        if code in (1049, "1049"):
            return True
    return False


def _create_database(url: URL) -> None:
    database = url.database
    if not database:
        return
    server_url = url.set(database=None)
    server_engine = _build_engine(server_url)
    try:
        with server_engine.connect() as conn:
            conn.execute(
                text(f"CREATE DATABASE IF NOT EXISTS `{database}` DEFAULT CHARACTER SET utf8mb4")
            )
            conn.commit()
    finally:
        server_engine.dispose()


def _attempt_connect(url: URL, label: str) -> Engine:
    LOG.debug("Trying %s database %s", label, _render_url(url))
    engine = _build_engine(url)
    try:
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
    except OperationalError as exc:
        if _is_unknown_database(exc):
            LOG.info("Database %s missing; attempting to create.", _render_url(url))
            _create_database(url)
            with engine.connect() as conn:
                conn.execute(text("SELECT 1"))
        else:
            engine.dispose()
            raise
    return engine


def _is_loc_environment() -> bool:
    """Determine whether to use the local database connection."""
    for value in (
        os.getenv("IS_LOC"),
        os.getenv("APP_ENV"),
        os.getenv("ENV"),
        os.getenv("RUN_ENV"),
    ):
        if not value:
            continue
        lowered = value.strip().lower()
        if lowered in {"loc", "local", "1", "true", "yes"}:
            return True
    return False


def _select_db_url() -> Tuple[str, URL]:
    if ENV_DATABASE_URL:
        return "env", make_url(ENV_DATABASE_URL)
    if _is_loc_environment():
        return "local", make_url(LOCAL_DB_URL)
    return "primary", make_url(PRIMARY_DB_URL)


def _initialise_engine() -> Tuple[Engine, str]:
    label, url = _select_db_url()
    try:
        engine = _attempt_connect(url, label)
        LOG.info("Connected to %s database: %s", label, _render_url(url))
        return engine, _render_url(url)
    except (OperationalError, SQLAlchemyError) as exc:
        LOG.error(
            "Unable to connect to %s database (%s) and no fallback is configured: %s",
            label,
            _render_url(url),
            exc,
        )
        raise
    except Exception as exc:  # pragma: no cover - defensive path
        LOG.exception(
            "Unexpected error connecting to %s database %s and no fallback is configured.",
            label,
            _render_url(url),
        )
        raise


ENGINE, DATABASE_URL = _initialise_engine()

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=ENGINE, future=True)
Base = declarative_base()


def get_engine() -> Engine:
    """Return the active SQLAlchemy engine."""
    return ENGINE


def init_db() -> None:
    """Initialise database schema if models are available."""

    try:
        from app.db.models import tool_record  # noqa: F401
        from app.db.models import param_settings  # noqa: F401
    except Exception as exc:
        LOG.debug("Optional tool models not initialised: %s", exc)

    Base.metadata.create_all(bind=ENGINE)
    try:
        from app.db.models import MzPoliShineDB

        MzPoliShineDB.Base.metadata.create_all(bind=ENGINE)
    except Exception as exc:  # pragma: no cover - optional import for autogenerated models
        LOG.debug("Optional MzPoliShineDB models not initialised: %s", exc)


def create_engine_ensuring_database(db_url: str) -> Engine:
    """Create an Engine; create DB if it doesn't exist.

    For MySQL URLs, if connecting raises an unknown-database error,
    connect to the server without a database, create it, and retry.
    """
    url = make_url(db_url)
    return _attempt_connect(url, "custom")
