from typing import Protocol, Callable, Optional
import numpy as np

FrameCallback = Callable[[np.ndarray], None]

class ICamera(Protocol):
    def open(self) -> None: ...
    def close(self) -> None: ...
    def start_stream(self, cb: FrameCallback) -> None: ...
    def stop_stream(self) -> None: ...
    def set_param(self, key: str, value): ...
