from typing import Protocol

class IIO(Protocol):
    def read(self, name: str) -> bool: ...
    def write(self, name: str, value: bool) -> None: ...
    def read_many(self, names: list[str]) -> dict[str, bool]: ...
    def write_mask(self, mask: dict[str, bool]) -> None: ...
