from typing import Protocol, Tuple

class IMotionController(Protocol):
    def home(self) -> None: ...
    def move_abs(self, x: float, y: float, z: float = 0.0, theta: float = 0.0) -> None: ...
    def wait_done(self, timeout: float = 10.0) -> bool: ...
    def status(self) -> Tuple[float, float, float, float]: ...
    def set_soft_limits(self, xmin: float, xmax: float, ymin: float, ymax: float) -> None: ...
    def set_speed(self, v_fast: float, v_work: float) -> None: ...
    def jog(self, axis: str, direction: int, speed: float) -> None: ...
    def set_work_origin(self) -> None: ...
