from typing import Protocol

class ISpindle(Protocol):
    def set_rpm(self, rpm: int) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def temperature(self) -> float: ...
    def rpm_actual(self) -> int: ...
