[project]
name = "Copper-Particle-Positioning-Grinding-System"

[tool.pyside6-project]
files = [
            "config.json",
            "main.py",
            "qml.qrc",
            "resource.qrc",
            "src.qrc",
]
